# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-12 14:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название конкурса')),
                ('comp_type', models.IntegerField(choices=[(1, 'Фотоконкурс'), (2, 'Литературный конкурс'), (3, 'Видеоконкурс'), (4, 'Аудиоконкурс')], default=1, verbose_name='тип конкурса')),
                ('start_date', models.DateTimeField(verbose_name='дата и время начала')),
                ('end_date', models.DateTimeField(verbose_name='дата и время окончания')),
                ('is_active', models.BooleanField(default=False, verbose_name='активен')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_competitions', to=settings.AUTH_USER_MODEL, verbose_name='кем организован')),
            ],
            options={
                'verbose_name_plural': 'Конкурсы',
                'verbose_name': 'Конкурс',
            },
        ),
        migrations.CreateModel(
            name='ParticipateRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, verbose_name='одобрено')),
                ('comment', models.TextField(verbose_name='комментарий')),
                ('content', models.FileField(upload_to='upload/', verbose_name='файл')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_part_requests', to='vote_app.Competition', verbose_name='конкурс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'verbose_name': 'Заявка',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='номер телефона')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Профили',
                'verbose_name': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participate_votes', to='vote_app.ParticipateRequest', verbose_name='заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name_plural': 'Голоса',
                'verbose_name': 'Голос',
            },
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set([('user', 'request')]),
        ),
    ]
